name: Rust Check

on:
  push:
    branches: [main, v*]
  pull_request:
    branches: [main, v*]

jobs:
  rust-check:
    runs-on: windows-latest
    defaults:
      run:
        working-directory: src-tauri
    steps:
      - name: Checkout repository
        uses: actions/checkout@34e114876b0b11c390a56381ad16ebd13914f8d5 # v4.3.1

      - name: Setup mise
        uses: jdx/mise-action@146a28175021df8ca24f8ee1828cc2a60f980bd5 # v3.5.1

      - name: Rust cache
        uses: swatinem/rust-cache@779680da715d629ac1d338a641029a2f4372abb5 # v2.8.2
        with:
          workspaces: "./src-tauri -> target"

      - name: Install Rust dependencies
        run: cargo fetch

      - name: Rust format check
        run: cargo fmt --all -- --check

      - name: Rust check
        run: cargo check
